data:
  channel_id: UCbFwe3COkDrbNsbMyGNCsDg
  ignore_word_list:
    - "^[0-9]+$"
    - "^(ある|する|みる|なる|ない|これ|やる|いる|どう|そう|くる|いく)$"
    - "^(evil|resident|Literature|Club|着信|ニア|たー|)$"
  min_word_occur: 3
  before_date: 2018-08-27
